name: Test Assignment Part A

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-A-question-1:
    name: Test PART A Question 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Q1 Tests
        run: |
          cd Submissions/A/Assignment2PartA/Q1
          for input_file in sample*_in.txt; do
            test_name="${input_file%_in.txt}"
            python ../../q1.py < "$input_file" > actual_output.txt
            diff -w actual_output.txt "${test_name}_out.txt" || exit 1
          done

  test-A-question-2:
    name: Test PART A Question 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Q2 Tests
        run: |
          cd Submissions/A/Assignment2PartA/Q2
          for input_file in sample*_in.txt; do
            test_name="${input_file%_in.txt}"
            python ../../q2.py < "$input_file" > actual_output.txt
            diff -w actual_output.txt "${test_name}_out.txt" || exit 1
          done

  test-A-question-3:
    name: Test PART A Question 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Q3 Tests
        run: |
          cd Submissions/A/Assignment2PartA/Q3
          for input_file in sample*_in.txt; do
            test_name="${input_file%_in.txt}"
            python ../../q3.py < "$input_file" > actual_output.txt
            diff -w actual_output.txt "${test_name}_out.txt" || exit 1
          done

  test-A-question-4:
    name: Test PART A Question 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Q4 Tests
        run: |
          cd Submissions/A/Assignment2PartA/Q4
          for input_file in sample*_in.txt; do
            test_name="${input_file%_in.txt}"
            # For Q4 that uses model JSON files
            python ../../q4.py < "$input_file" > actual_output.txt
            diff -w actual_output.txt "${test_name}_out.txt" || exit 1
          done